version: '2'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
